version: '3'
services:
  user-api:
    image: user-api
    container_name: user-api
    build:
      context: ""
      dockerfile: user-api/Dockerfile
    ports:
      - "8000:8000"
  relational-user-service:
    image: relational-user-service
    container_name: relational-user-service
    build:
      context: ""
      dockerfile: relational-user-service/Dockerfile
    ports:
      - "8005:8005"
  graph-user-service:
    image: graph-user-service
    container_name: graph-user-service
    build:
      context: ""
      dockerfile: graph-user-service/Dockerfile
    ports:
      - "8010:8010"
