server:
  port: 3000

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:////Users/artembelmeha/diploma/compare-app/config-service/src/main/resources/config
